### PR TITLE
Give explicit names to all mutations.

### PR DESCRIPTION
**Pull request by SachaG**
I got an error (`Error: GraphQL error: No operation named ""`) because of an unnamed mutation, so I thought I'd give all of them names.

### CODE REVIEW

**Comment by SachaG** [comment]
I also fixed another error (`Error: GraphQL error: Nullability mismatch on variable $lineItems and argument lineItems ([CheckoutLineItemInput!] / [CheckoutLineItemInput!]!)`) by replacing `[CheckoutLineItemInput!]` with `[CheckoutLineItemInput!]!`.

**Comment by swalkinshaw** [comment]
https://github.com/Shopify/storefront-api-examples/pull/21 will be merged tomorrow and it fixes the variable type mismatches for every example.

I think there's also a server-side fix here to not treat an empty string (`""`) as an actual `operationName`. I'll leave this open though since might be good to merge anyway.

**Comment by swalkinshaw** [comment]
FYI the Storefront API now treats an empty string `operationName` as a query without an operation name.

**Comment by swalkinshaw** [comment]
#21 was merged. The only change which we might want from this PR is the mutation names just for descriptive reasons. Feel free to either update this or close.

**Comment by SachaG** [comment]
Updated the PR.

**Comment by swalkinshaw** [comment]
Thanks 👍

**Pull request merged**
