### PR TITLE
Angular 5 Storefront API example

### PR DESCRIPTION
**Pull request by JsssCode**
Angular 4 Storefront API example

### CODE REVIEW

**Comment by swalkinshaw** [comment]
I don't know anything about Angular 4 but I tried to get this running according to the README.

After an `npm install`, I ran `npm start` and get the following error:

```plain
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (/Users/scott/dev/storefront-api-examples/angular-graphql-client/node_modules/typescript/lib/typescript.js:15457:109)
    at parseSourceFileWorker (/Users/scott/dev/storefront-api-examples/angular-graphql-client/node_modules/typescript/lib/typescript.js:15389:26)
    at Object.parseSourceFile (/Users/scott/dev/storefront-api-examples/angular-graphql-client/node_modules/typescript/lib/typescript.js:15338:26)
    at Object.createSourceFile (/Users/scott/dev/storefront-api-examples/angular-graphql-client/node_modules/typescript/lib/typescript.js:15192:29)
    at VirtualFileStats.getSourceFile (/Users/scott/dev/storefront-api-examples/angular-graphql-client/node_modules/@ngtools/webpack/src/compiler_host.js:66:35)
    at WebpackCompilerHost.getSourceFile (/Users/scott/dev/storefront-api-examples/angular-graphql-client/node_modules/@ngtools/webpack/src/compiler_host.js:213:38)
    at findSourceFile (/Users/scott/dev/storefront-api-examples/angular-graphql-client/node_modules/typescript/lib/typescript.js:67909:29)
    at processImportedModules (/Users/scott/dev/storefront-api-examples/angular-graphql-client/node_modules/typescript/lib/typescript.js:68056:25)
    at findSourceFile (/Users/scott/dev/storefront-api-examples/angular-graphql-client/node_modules/typescript/lib/typescript.js:67937:17)
    at processImportedModules (/Users/scott/dev/storefront-api-examples/angular-graphql-client/node_modules/typescript/lib/typescript.js:68056:25)
    at findSourceFile (/Users/scott/dev/storefront-api-examples/angular-graphql-client/node_modules/typescript/lib/typescript.js:67937:17)
    at processImportedModules (/Users/scott/dev/storefront-api-examples/angular-graphql-client/node_modules/typescript/lib/typescript.js:68056:25)
    at findSourceFile (/Users/scott/dev/storefront-api-examples/angular-graphql-client/node_modules/typescript/lib/typescript.js:67937:17)
    at processImportedModules (/Users/scott/dev/storefront-api-examples/angular-graphql-client/node_modules/typescript/lib/typescript.js:68056:25)
    at findSourceFile (/Users/scott/dev/storefront-api-examples/angular-graphql-client/node_modules/typescript/lib/typescript.js:67937:17)
    at processImportedModules (/Users/scott/dev/storefront-api-examples/angular-graphql-client/node_modules/typescript/lib/typescript.js:68056:25)
```

This is using Node v8.5.0 and npm 5.4.2.

**Comment by JsssCode** [comment]
My mistake. Files added. Readme.md updated.

**Comment by royjulien** [comment]
Update to Angular-cli 5 ;))))

**Comment by swalkinshaw** [comment]
Sorry @JsssCode, I had forgotten about this until your recent commits. I'll give this another look soon. But last time I tried it out, it was using different styling from our other examples. They all use the same css from https://github.com/Shopify/storefront-api-examples/tree/master/shared (and same HTML structure).

Is that possible to do with this Angular example?

**Comment by JsssCode** [comment]
@swalkinshaw Yes, it is possible, will work on this

**Comment by JsssCode** [comment]
@swalkinshaw, it's done. Now I use general css and html structure is the same as in other samples.

**Comment by swalkinshaw** [comment]
Tried it out and it mostly looks good. I had a few styling issues with the Cart sidebar though.

I'm going to merge this since it's definitely useful as an Angular example anyway. There can always be follow-up fixes 😄 

Thank you!

**Comment by JsssCode** [comment]
@swalkinshaw, thanks. Will try to fix

**Pull request merged**
