### PR TITLE
update react-js-buy's shopify-buy dependency use of api

### PR DESCRIPTION
**Pull request by Strangehill**

### CODE REVIEW

**Comment by swalkinshaw** [comment]
still WIP?

**Comment by Strangehill** [comment]
yes. At the moment I'm getting the following error when I try to select a product variant and unsure how to proceed:
`Uncaught TypeError: Cannot read property 'Helpers' of undefined at Product.handleOptionChange`

**Comment by Strangehill** [comment]
I got past this error by passing down client as a prop from App component, to products, to product... not sure if this is the right way. (besides being new to js-buy I'm new to react)

**Comment by Strangehill** [comment]
It seems this error existed already, I've reported it #54 

Which means, this is ready for review. I poked around the page manually and followed the errors, so I likely overlooked some other necessary changes.

**Comment by swalkinshaw** [comment]
Looks good, thanks!

**Pull request merged**
